// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cb730afb-0ee7-42d9-9436-80f1460f38d6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_O7hTE1XX0",
    "aws_user_pools_web_client_id": "267vapsep1kbkmgbl4a67ml3ni"
};


export default awsmobile;
